baseURL = "https://thamle.live/"
languageCode = "en-us"
theme = "amethyst"
title = "Tham Le - Learning Through Code"
disablePathToLower = true
enableGitInfo = true
ignoreFiles = ["/README\\.md$"]

mainSections = ["ctf-events"] # Added this line

# Amethyst theme settings
[params]
  name = "Tham Le"
  title = "👨‍💻 Tham Le - Learning Through Code"
  description = "Software engineer learning through building, breaking, and understanding systems. From ocean science to code."
  
  # Theme features
  enableLinkPreview = true
  enableLatex = true
  enableCodeBlockTitle = true
  enableCodeBlockCopy = true
  enableCallouts = true
  enableFooter = true
  enableContextualBacklinks = true
  enableRecentNotes = true
  enableGitHubEdit = true
  enableMermaid = true
  enableSPA = false # Single Page Application mode

  # GitHub settings
  GitHubLink = "https://github.com/tham-le/thamle-portfolio" 
  BookRepo = "https://github.com/tham-le/thamle-portfolio"
  BookEditPath = "edit/main"
  BookDateFormat = "January 2, 2006"

  # Sidebar and Table of Contents
  BookToC = true # Show ToC on the right
  BookSection = "/" # Render all sections in the menu

  # Comments
  BookComments = false

  # Footer links
  [[params.links]]
    link_name = "GitHub"
    link = "https://github.com/tham-le"
  [[params.links]]
    link_name = "LinkedIn"
    link = "https://linkedin.com/in/tham42"
  [[params.links]]
    link_name = "Email"
    link = "mailto:thamle.work@gmail.com"

# Main menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20
[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 30
[[menu.main]]
  name = "CTF Writeups"
  url = "/ctf-events/"
  weight = 40
[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 50
[[menu.main]]
  name = "Resume"
  url = "/thamle_resume.pdf"
  weight = 60
  
# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Markup
[markup]
  [markup.goldmark.renderer]
    unsafe = true # Needed for mermaid/katex shortcodes
  [markup.tableOfContents]
    startLevel = 1

# Permalinks
[permalinks]
  projects = "/projects/:slug/"
  notes = "/notes/:slug/"
  ctf-events = "/ctf-events/:slug/"

[build]
  writeStats = true
  [build.buildStats]
    enable = true
  [[build.processing.js]]
    source = "assets/ts/main.ts"
    target = "js/main.js"