baseURL = "https://thamle.live/"
languageCode = "en-us"
theme = "hugo-theme-stack"
title = "Tham Le - Software Engineer & Cybersecurity Enthusiast"
copyright = "© 2025 Tham Le. All rights reserved."

# Theme i18n support
DefaultContentLanguage = "en"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30
[[menu.main]]
identifier = "ctf"
name = "CTF Writeups"
url = "/ctf/"
weight = 40
[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/ThamLE_resume.pdf"
weight = 50
[menu.main.params]
newTab = true

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = false

# Pagination
[pagination]
pagerSize = 9

# Permalinks for different content types
[permalinks]
projects = "/projects/:slug/"
ctf = "/ctf/:sections[1:]/:slug/"
blog = "/blog/:slug/"

# Main sections for homepage
[params]
mainSections = ["projects", "ctf", "blog"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[params.sidebar]
emoji = "👨‍💻"
subtitle = "Software Engineer | Cybersecurity Enthusiast"

# Color scheme configuration for dark mode
[params.colorScheme]
toggle = true
default = "auto"

# Footer configuration
[params.footer]
since = 2024
customText = "Building secure and innovative solutions"

# Date format
[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

# Article configuration
[params.article]
math = true
toc = true
readingTime = true
[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# Comments (you can enable later)
[params.comments]
enabled = false
provider = "utterances"

# Social links (global)
[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/tham-le"
[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/tham42"
[menu.social.params]
icon = "user"

[[menu.social]]
identifier = "email"
name = "Email"
url = "mailto:thamle.work@gmail.com"
[menu.social.params]
icon = "messages"

# Taxonomies for content organization
[taxonomies]
event = "events"
category = "categories"
tag = "tags"

# Image processing
[imaging]
quality = 95
resampleFilter = "CatmullRom"

# Security
[security]
enableInlineShortcodes = false
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
[security.funcs]
getenv = ['^HUGO_', '^CI$']

# Markup
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true
[markup.highlight]
style = "github-dark"
lineNos = true
lineNumbersInTable = true
codeFences = true
