name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ctf_app/**'
      - 'ctf_site/**'
      - 'project_site/**'
      - 'public/**'
      - '.github/workflows/ci-pull-request.yml'

jobs:
  lint-project-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project_site
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # - name: Install dependencies
      #   run: npm install
      # - name: Run linter
      #   run: npm run lint

  lint-ctf-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ctf_site
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # - name: Install dependencies
      #   run: npm install
      # - name: Run linter
      #   run: npm run lint

  lint-flutter-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ctf_app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
      - name: Run linter
        run: flutter analyze