name: Deploy Project Showcase Site

on:
  push:
    branches:
      - main
    paths:
      - 'project_site/**'
      - '.github/workflows/deploy-project-site.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THAMLE_PORTFOLIO }}'
          channelId: live
          projectId: thamle-portfolio
          target: project 