name: Deploy Main Portfolio Site

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - 'firebase.json'
  workflow_dispatch:

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THAMLE_PORTFOLIO }}
        projectId: thamle-portfolio
        target: main
