name: Deploy Main Portfolio Site

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - '.github/workflows/deploy-main-site.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    if: github.repository == 'tham-le/thamle-portfolio'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build and deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting:main --token "$FIREBASE_TOKEN"
