name: 🎯 Deploy Flutter Showcase App

on:
  # SECURITY: Only deploy after CI/CD validation passes
  workflow_run:
    workflows: ["🧪 CI/CD - Code Validation"]
    types: [completed]
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "DEPLOY_FLUTTER" to confirm Flutter app deployment'
        required: true
        default: ''
      bypass_validation:
        description: 'EMERGENCY: Bypass CI/CD validation? (DANGER)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  check-validation:
    runs-on: ubuntu-latest
    outputs:
      validation-passed: ${{ steps.check.outputs.passed }}
    steps:
    - name: Check CI/CD Validation Status
      id: check
      run: |
        if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "✅ CI/CD validation passed"
            echo "passed=true" >> $GITHUB_OUTPUT
          else
            echo "❌ CI/CD validation failed"
            echo "passed=false" >> $GITHUB_OUTPUT
          fi
        elif [[ "${{ github.event.inputs.bypass_validation }}" == "true" ]] && [[ "${{ github.event.inputs.confirm_deploy }}" == "DEPLOY_FLUTTER" ]]; then
          echo "⚠️ EMERGENCY: Bypassing CI/CD validation for Flutter deployment"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "❌ No valid trigger or bypass"
          echo "passed=false" >> $GITHUB_OUTPUT
        fi

  deploy-flutter-showcase:
    runs-on: ubuntu-latest
    needs: check-validation
    # SECURITY: Only deploy if validation passed
    if: needs.check-validation.outputs.validation-passed == 'true'
    
    steps:
    - name: Flutter Showcase Notice
      run: |
        echo "🚨 NOTICE: This workflow deploys the Flutter CTF app for showcase purposes only."
        echo "🌐 The main CTF site at ctf.thamle.live is served by the HTML version."
        echo "🎯 This Flutter app will be deployed to a separate showcase URL."
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
        
    - name: Copy writeups to Flutter assets
      run: |
        mkdir -p ctf_app/assets/writeups
        if [ -d "ctf_app/assets/writeups" ] && [ "$(ls -A ctf_app/assets/writeups)" ]; then
          echo "📁 Writeups already present in CTF app assets"
          ls -la ctf_app/assets/writeups/
        else
          echo "⚠️ No writeups found in ctf_app/assets/writeups/"
        fi
        
    - name: Get Flutter dependencies
      working-directory: ./ctf_app
      run: flutter pub get
      
    - name: Build Flutter web app
      working-directory: ./ctf_app
      run: flutter build web --release --base-href /
      
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THAMLE_PORTFOLIO }}
        projectId: thamle-portfolio
        target: ctf-flutter
        channelId: live
