name: Deploy CTF Site

on:
  push:
    branches: [ main ]
    paths:
      - 'ctf_site/**'
      - 'external-writeups/**'
  workflow_dispatch:

jobs:
  deploy-ctf-site:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Copy writeups to CTF site
      run: |
        mkdir -p ctf_site/assets/writeups
        cp -r external-writeups/* ctf_site/assets/writeups/
        
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THAMLE_PORTFOLIO }}
        projectId: thamle-portfolio
        target: ctf-writeups
        channelId: live
