name: Sync, Build, and Deploy Portfolio

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  schedule:
    # Daily sync at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  sync-build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false  # We'll handle submodules manually
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Setup Git for submodules
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Initialize and update submodules
      run: |
        # Initialize submodules
        git submodule init
        
        # Update theme submodule
        git submodule update themes/hugo-theme-stack
        
        # Update CTF writeups submodule if it exists
        if git submodule status content/ctf-external >/dev/null 2>&1; then
          git submodule update content/ctf-external
        else
          echo "CTF writeups submodule not found, skipping..."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: Setup environment
      run: |
        echo "GITHUB_TOKEN=${{ secrets.TOKEN_GITHUB }}" >> .env
        echo "GITHUB_USERNAME=tham-le" >> .env
        echo "HUGO_ENV=production" >> .env

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Sync all content
      run: |
        chmod +x ./sync-all.sh
        ./sync-all.sh
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.129.0'
        extended: true
    
    - name: Test Hugo build
      run: |
        echo "🔍 Testing Hugo build..."
        hugo --minify --environment production
        echo "✅ Hugo build successful!"
    
    - name: Verify build output
      run: |
        echo "🔍 Verifying build output..."
        if [ ! -d "public" ]; then
          echo "❌ Public directory not created"
          exit 1
        fi
        
        if [ ! -f "public/index.html" ]; then
          echo "❌ Index.html not generated"
          exit 1
        fi
        
        echo "✅ Build verification successful!"
        echo "📊 Build statistics:"
        echo "- Total files: $(find public -type f | wc -l)"
        echo "- HTML files: $(find public -name "*.html" | wc -l)"
        echo "- CSS files: $(find public -name "*.css" | wc -l)"
        echo "- JS files: $(find public -name "*.js" | wc -l)"
    
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
        projectId: 'thamle-portfolio'
        channelId: live
