name: Sync CTF Writeups

on:
  push:
    paths:
      - 'external-writeups/**'
  workflow_dispatch:

jobs:
  sync-writeups:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install pyyaml
        
    - name: Sync writeups
      run: |
        python3 << 'PYTHON_SCRIPT'
        import os
        import json
        import yaml

        def find_writeups(directory):
            writeups = []
            for root, _, files in os.walk(directory):
                for file in files:
                    if file.endswith('.md'):
                        path = os.path.join(root, file)
                        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                            content = f.read()
                        
                        try:
                            # Extract YAML frontmatter
                            _, frontmatter_str, _ = content.split('---', 2)
                            metadata = yaml.safe_load(frontmatter_str)
                        except ValueError:
                            # No frontmatter, use basic info
                            metadata = {
                                'title': os.path.basename(path).replace('.md', ''),
                                'event': os.path.basename(os.path.dirname(os.path.dirname(path))),
                                'category': os.path.basename(os.path.dirname(path)),
                                'tags': []
                            }

                        writeups.append({
                            'title': metadata.get('title', ''),
                            'event': metadata.get('event', ''),
                            'category': metadata.get('category', ''),
                            'tags': metadata.get('tags', []),
                            'path': os.path.relpath(path, directory)
                        })
            return writeups

        writeups = find_writeups('external-writeups')

        with open('ctf_site/assets/writeups/index.json', 'w') as f:
            json.dump(writeups, f, indent=2)

        PYTHON_SCRIPT
